### ISSUE TITLE
Avoid critical display errors

### ISSUE THREAD

**Issue by Nebelix** [Nebelix/aquarium#5]
After some days of runtime the following error stopped the script:
```
Traceback (most recent call last):
  File "/home/pi/Templates/aquarium.py", line 68, in <module>
    lcd.lcd_display_string('  {0:0.1f}'.format(mintemp) +'  {0:0.1f}'.format(maxtemp), 3,8)
  File "/home/pi/Templates/lcddriver.py", line 159, in lcd_display_string
    self.lcd_write(ord(char), Rs)
  File "/home/pi/Templates/lcddriver.py", line 136, in lcd_write
    self.lcd_write_four_bits(mode | (cmd & 0xF0))
  File "/home/pi/Templates/lcddriver.py", line 132, in lcd_write_four_bits
    self.lcd_strobe(data)
  File "/home/pi/Templates/lcddriver.py", line 127, in lcd_strobe
    self.lcd_device.write_cmd(((data & ~En) | LCD_BACKLIGHT))
  File "/home/pi/Templates/lcddriver.py", line 34, in write_cmd
    self.bus.write_byte(self.addr, cmd)
OSError: [Errno 121] Remote I/O error
```
Probably communication to display was shortly lost. All print commands should be in handled with "try", like reading temperature sensor. And counting soft error up on fail.

**Comment by Nebelix** [comment]
Occured again after 3 days running, shortly after internet router was switched on.
```
Traceback (most recent call last):
  File "/home/pi/Templates/aquarium.py", line 53, in <module>
    lcd.lcd_display_string('T={0:0.1f}'.format(temperature) +chr(223)+"C", 3)
  File "/home/pi/Templates/lcddriver.py", line 159, in lcd_display_string
    self.lcd_write(ord(char), Rs)
  File "/home/pi/Templates/lcddriver.py", line 137, in lcd_write
    self.lcd_write_four_bits(mode | ((cmd << 4) & 0xF0))
  File "/home/pi/Templates/lcddriver.py", line 131, in lcd_write_four_bits
    self.lcd_device.write_cmd(data | LCD_BACKLIGHT)
  File "/home/pi/Templates/lcddriver.py", line 34, in write_cmd
    self.bus.write_byte(self.addr, cmd)
OSError: [Errno 121] Remote I/O error
```
